config/routes.rb
Rails.application.routes.draw do
  root   'home#index'
  get    'edit'    => 'home#edit'
  get    'login'   => 'sessions#new'
  post   'login'   => 'sessions#create'
  delete 'logout'  => 'sessions#destroy'
  get    'signup'  => 'users#new'
  post   'signup'  => 'users#create'
  
  get    'projects/new/:expId' => 'projects#new'
  resources :profiles , only: [:update, :index]
  resources :educations , only: [:new]
  resources :experiences , only: [:new]
  resources :projects , only: [:new]
end

app/models/user.rb
class User < ApplicationRecord

    VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
    
    before_save { self.email = email.downcase }
    
    validates(:name, presence: true)
    validates(:email, presence: true, format: { with: VALID_EMAIL_REGEX }, uniqueness: { case_sensitive: false })
    validates(:password, presence: true, length: { minimum: 8 })

    # adds password fields
    has_secure_password

    has_one :profile, dependent: :destroy
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

    def new
    end

    def create
        if params[:session][:password] == params[:session][:password_redundant]
            @user = User.new(name: params[:session][:name], email: params[:session][:email], password: params[:session][:password])
            @user.profile = Profile.new
            if @user.save
                log_in(@user)
                redirect_to(edit_path)
            else
                flash.now[:danger] = 'Invalid data. Try again with correct details'
                render :signup, status: :unprocessable_entity
            end
        else
            flash.now[:danger] = 'Passwords do not match'
            render :signup, status: :unprocessable_entity
        end
    end
end

app/views/users/new.html.erb
<div class="w-screen h-screen flex justify-center items-center">
    <div class="flex flex-col max-w-md px-4 py-8 bg-white rounded-lg shadow dark:bg-gray-800 sm:px-6 md:px-8 lg:px-10">
        <div class="self-center mb-2 text-xl font-light text-gray-800 sm:text-2xl dark:text-white">
             Create a new account
        </div>
        <span class="justify-center text-sm text-center text-gray-500 flex-items-center dark:text-gray-400">
        Already have an account ? <span class="text-indigo-500" ><%= link_to "Log in", login_path(@session) %> </span>
        </span>
        <div class="p-6 mt-8">
            <%= form_for(:session, url: signup_path) do |form| %>
                <div class="flex flex-col mb-2">
                    <div class="flex relative">
                        <%= form.text_field :name, value: '', class: 'rounded-r-lg flex-1 appearance-none border border-gray-300 w-full py-2 px-4 bg-white text-gray-700 placeholder-gray-400 shadow-sm text-base focus:outline-none focus:ring-2 focus:ring-purple-600 focus:border-transparent', placeholder: 'Name' %>
                    </div>
                </div>

                <div class="flex flex-col mb-2">
                    <div class="flex relative ">
                        <%= form.email_field :email, value: '', class: 'rounded-r-lg flex-1 appearance-none border border-gray-300 w-full py-2 px-4 bg-white text-gray-700 placeholder-gray-400 shadow-sm text-base focus:outline-none focus:ring-2 focus:ring-purple-600 focus:border-transparent', placeholder: 'Email' %>
                    </div>
                </div>
                <div class="flex flex-col mb-2">
                    <div class="flex relative ">
                        <%= form.password_field :password, value: '', class: 'rounded-r-lg flex-1 appearance-none border border-gray-300 w-full py-2 px-4 bg-white text-gray-700 placeholder-gray-400 shadow-sm text-base focus:outline-none focus:ring-2 focus:ring-purple-600 focus:border-transparent', placeholder: 'Password' %>
                    </div>
                </div>
                
                <div class="flex flex-col mb-6">
                    <div class="flex relative ">
                        <%= form.password_field :password_redundant, value: '', class: 'rounded-r-lg flex-1 appearance-none border border-gray-300 w-full py-2 px-4 bg-white text-gray-700 placeholder-gray-400 shadow-sm text-base focus:outline-none focus:ring-2 focus:ring-purple-600 focus:border-transparent', placeholder: 'Password again' %>
                    </div>
                </div>

                <div class="flex w-full">
                    <%= form.submit "Sign Up", class: "py-2 px-4  bg-purple-600 hover:bg-purple-700 focus:ring-purple-500 focus:ring-offset-purple-200 text-white w-full transition ease-in duration-200 text-center text-base font-semibold shadow-md focus:outline-none focus:ring-2 focus:ring-offset-2  rounded-lg" %>
                </div>
            <% end %>
        </div>
    </div>
</div>